### ISSUE TITLE
[1.19.2] Ticking Entity Crash (Can't find attribute apotheosis:current_hp_damage)

### ISSUE THREAD

**Issue by Gbergz** [Shadows-of-Fire/Apotheosis#685]
Title^

Stood still in my world and suddeny it crashed.

Apotheosis: 6.0.0 | https://www.curseforge.com/minecraft/mc-mods/apotheosis/files/4036357
Placebo: 7.0.1
Minecraft: 1.19.2
Forge: 43.1.39

Crash-Report: https://gist.github.com/Gbergz/0ce1769ac55868ad3d83c2462a126d5c

**Comment by P3rf3ctXZer0** [comment]
https://github.com/P3rf3ctXZer0/Fiction.Friction/issues/16

**Comment by Shadows-of-Fire** [comment]
I'll need to look into this a bit more, but this is likely similar to #633 where the other mod's mob isn't registering attributes correctly.

**Comment by P3rf3ctXZer0** [comment]
Although I agree some mods don't play nice maybe just have your mod ignore mods that don't register correctly make a skip fall back and auto blacklist. Most mod devs shrug if you say; by the way Shadows-of-Fire says your doing your code wrong please make a patch. 

Also I find it ironic you bring up evilcraft as I have actually blacklisted it from my modpacks due to causing major instability over time.

Honestly if you just made the super mobs spawn module a separate mod that would be cool too since its the only thing I care about.

**Comment by Shadows-of-Fire** [comment]
Resolved externally

**Comment by P3rf3ctXZer0** [comment]
Even if it was solved externally it's still a short term solution.

**Comment by P3rf3ctXZer0** [comment]
This is still an issue just with other mods. That is why I said this was a short term fix. Let me know when you decide to add fallback logic on mods that add mobs.

**Comment by Shadows-of-Fire** [comment]
I am not going to be applying bandaids to apoth to fix issues in other mods.  You can report issues about improper registration to other mods as the problem arises.
